const translations = {
    tr: {
        home: "Anasayfa",
        about: "Hakkımda",
        projects: "Projeler",
        gallery: "Galeri",
        blog: "Blog",
        contact: "İletişim",
        welcome: "Hoşgeldiniz",
        welcome_text: "Kişisel web siteme hoşgeldiniz. Burada projelerimi ve blog yazılarımı bulabilirsiniz.",
        toggle_theme: "Tema Değiştir",
        toggle_lang: "EN",
        toggle_style: "Görünüm: Modern",
        about_title: "Hakkımda",
        about_text: "Merhaba, ben bir web geliştiricisiyim. HTML, CSS ve JavaScript kullanarak web siteleri tasarlıyorum.",
        projects_title: "Projelerim",
        gallery_title: "Galeri",
        blog_title: "Blog Yazıları",
        contact_title: "İletişim",
        name: "Adınız",
        email: "E-posta",
        message: "Mesajınız",
        send: "Gönder",
        footer_text: "Tüm hakları saklıdır.",
        modal_close: "Kapat",
        back_to_blog: "← Blog'a Dön",
        retro_mode: "Görünüm: Eski",
        modern_mode: "Görünüm: Modern",
        view_repo: "Repoyu İncele",
        stars: "Yıldız",
        forks: "Fork",
        no_description: "Açıklama yok.",
        personal_intro_title: "Kişisel Tanıtım",
        personal_intro_text: "Merhaba! Ben Ali Kemal Kara. Tuzla Meslek Lisesi'nde yazılım bölümü okudum ve şu anda Akdeniz Üniversitesi'nde Bilgisayar Programcılığı bölümünde eğitimime devam ediyorum. Yazılım geliştirme alanında kendimi sürekli geliştirmeye odaklı bir öğrenciyim.",
        experience_title: "İş Deneyimi",
        experience_text: "NETAŞ'ta 10 ay boyunca Software Developer Intern olarak çalıştım. Bu süreçte yazılım geliştirme süreçlerini öğrendim, takım çalışması deneyimi kazandım ve profesyonel iş ortamında projeler geliştirdim.",
        education_title: "Eğitim",
        education_ongoing: "Devam Ediyor",
        education_graduated: "Mezun",
        skills_title: "Kullandığım Teknolojiler",
        photoshop_projects_title: "Photoshop Projeleri",
        latest_projects: "Son Projeler",
        gallery_preview: "Galeri Önizleme",
        read_more: "Devamını Oku",
        view_all_projects: "Tüm Projeleri Gör",
        view_gallery: "Galeriyi Görüntüle"
    },
    en: {
        home: "Home",
        about: "About",
        projects: "Projects",
        gallery: "Gallery",
        blog: "Blog",
        contact: "Contact",
        welcome: "Welcome",
        welcome_text: "Welcome to my personal website. Here you can find my projects and blog posts.",
        toggle_theme: "Toggle Theme",
        toggle_lang: "TR",
        toggle_style: "Style: Modern",
        about_title: "About Me",
        about_text: "Hello, I am a web developer. I design websites using HTML, CSS, and JavaScript.",
        projects_title: "My Projects",
        gallery_title: "Gallery",
        blog_title: "Blog Posts",
        contact_title: "Contact",
        name: "Your Name",
        email: "Email",
        message: "Message",
        send: "Send",
        footer_text: "All rights reserved.",
        modal_close: "Close",
        back_to_blog: "← Back to Blog",
        retro_mode: "Style: Retro",
        modern_mode: "Style: Modern",
        view_repo: "View Repo",
        stars: "Stars",
        forks: "Forks",
        no_description: "No description.",
        personal_intro_title: "Personal Introduction",
        personal_intro_text: "Hello! I am Ali Kemal Kara. I studied software at Tuzla Vocational High School and I am currently continuing my education in the Computer Programming department at Akdeniz University. I am a student focused on constantly improving myself in the field of software development.",
        experience_title: "Work Experience",
        experience_text: "I worked as a Software Developer Intern at NETAŞ for 10 months. During this process, I learned software development processes, gained teamwork experience and developed projects in a professional business environment.",
        education_title: "Education",
        education_ongoing: "Ongoing",
        education_graduated: "Graduated",
        skills_title: "Technologies Used",
        photoshop_projects_title: "Photoshop Projects",
        latest_projects: "Latest Projects",
        gallery_preview: "Gallery Preview",
        read_more: "Read More",
        view_all_projects: "View All Projects",
        view_gallery: "View Gallery"
    }
};
